version: "3.4"

services:
    redis-test:
        build: 
            context: ./
            dockerfile: ./docker/Dockerfile
        image: redis-test:latest
        environment:
            - REDIS_HOST=redis-server
        healthcheck:
            test: ["CMD", "curl","-f","http://localhost:3000/asd"]
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 40s
        networks:
            - frontend
            - backend
    redis-server:
        image: redis:latest
        # ports:
        #     - 6379:6379
        networks:
            - backend
    nginx:
        image: nginx:stable-alpine
        ports:
            - 3000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/log/nginx:/var/log/nginx
        depends_on:
            redis-test:
                condition: service_healthy

        networks:
            - frontend

networks:
    backend:
    frontend:
