version: "3.4"

services:
    redis-test:
        build: ./docker
        image: redis-test:latest
        networks:
            - demo-network
        ports:
            - 5000:3000
    redis-server:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - demo-network

networks:
    demo-network:
