version: "3.4"

services:
    redis-test:
        # build: 
        #     context: docker  
        image: redis-test:latest
        networks:
            - frontend
            - backend
    redis-server:
        image: redis:latest
        # ports:
        #     - 6379:6379
        networks:
            - backend
    nginx:
        image: nginx:stable-alpine
        ports:
            - 3000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/log/nginx:/var/log/nginx
        depends_on:
            - redis-test
        networks:
            - frontend

networks:
    backend:
    frontend:
